t_scene_info = [
	[cs_wait, 2],
	[cs_instance_create, 0, 0, "gui", d_text15],
	[cs_wait, 1],
	[cs_instance_destroy, d_text15],
	[cs_wait, 1],
	[cs_instance_create, 0, 0, "gui", d_text18],
	[cs_wait, 1],
	[cs_instance_destroy, d_text18],
	[cs_wait, 1],
	[cs_instance_create, 0, 0, "gui", d_text16],
	[cs_wait, 1],
	[cs_instance_destroy, d_text16],
	[cs_wait, 1],
	[cs_instance_create, 0, 0, "gui", d_text17],
	[cs_wait, 1],
	[cs_instance_destroy, d_text17],
	[cs_wait, 2],
	[cs_instance_create, x, y, "gui", o_fade4],
	[cs_wait, 2],
]