t_scene_info = [
	[cs_wait, 2],
	[cs_instance_create, 0, 0, "gui", d_text9],
	[cs_wait, 1],
	[cs_instance_destroy, d_text9],
	[cs_wait, 1],
	[cs_instance_create, 0, 0, "gui", d_text12],
	[cs_wait, 1],
	[cs_instance_destroy, d_text12],
	[cs_wait, 1],
	[cs_instance_create, 0, 0, "gui", d_text10],
	[cs_wait, 1],
	[cs_instance_destroy, d_text10],
	[cs_wait, 1],
	[cs_instance_create, 0, 0, "gui", d_text11],
	[cs_wait, 1],
	[cs_instance_destroy, d_text11],
]